name: Build

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # ESP-IDF versions and targets
        idf_ver: [ v5.2 ]
        idf_target: [ esp32, esp32s3 ]
    container: espressif/idf:release-${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build

      # attach the build artifacts as a workflow run artifact
      - name: Flash cmd
        run: |
          echo 'python -m esptool --chip esp32 -b 921600 --before default_reset --after hard_reset write_flash "@flash_args"' > build/flash.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: skidsteer-firmware-${{ matrix.idf_target }}
          path: |
            build/flash.txt
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/skidsteer-firmware.bin
            build/*flash_args
            build/flasher_args.json
          compression-level: 9
          if-no-files-found: error

  build-all:
    runs-on: ubuntu-latest
    needs:
      - build
    # Aggregating job only
    steps:
      - run: echo OK
