name: Build

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # ESP-IDF versions and targets
        idf_ver: [ v5.2 ]
        idf_target: [ esp32 ]
    container: espressif/idf:release-${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build

  build-all:
    runs-on: ubuntu-latest
    needs:
      - build
    # Aggregating job only
    steps:
      - run: echo OK
